const CANVAS_SIZE = 600;
const FRAME_RATE = 20;
const BASE_ANIMATION_FRAMES = 20;

let CANVAS_CENTER;
let QUADRANT_CENTERS;

let QUADRANT_CENTERS_Z;

let GRID_CENTERS;

let BASE_GOSPER;
let GOSPER_SCALE = 1 / Math.sqrt(7);
let GOSPER_ANGLE = 0.333473172251832115;

let BASE_DRAGON;

const EPS = 1e-5;